version: "3.9"

services:
  redis:
    image: redis:7
    container_name: ws_redis
    ports:
      - "6380:6379"

  websocket_server:
    build: .
    container_name: ws_server
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    stop_signal: SIGTERM
    stop_grace_period: 1800s
